### PR TITLE
Creating a new testing structure

### PR DESCRIPTION
**Pull request by makinde**
This diff does a couple things:
- It creates test file for every Model and Document method that we'll need to handle and test. These can be gradually filled in.
- It breaks helpers.js functions into separate files. Each one of those now has a corresponding test file.

In upcoming diffs, I'll move the existing tests into this new structure.

### CODE REVIEW

**Comment by brysgo** [comment]
Haven't been able to look at it in depth, but I'm a fan of the new structure.

**Review by brysgo — COMMENTED** [review]
I tried running the tests, and they pass despite an unhandled promise rejection.

```
✔ sanitizeDocumentList
✔ getUpdatePaths

index.test.js
(node:87895) UnhandledPromiseRejectionWarning: MongoError: ns not found
    at /Users/goldstein bryan/workspace/mongoose-authz/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:593:63
    at authenticateStragglers (/Users/goldstein bryan/workspace/mongoose-authz/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:516:16)
    at Connection.messageHandler (/Users/goldstein bryan/workspace/mongoose-authz/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:552:5)
    at emitMessageHandler (/Users/goldstein bryan/workspace/mongoose-authz/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:309:10)
    at Socket.<anonymous> (/Users/goldstein bryan/workspace/mongoose-authz/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:452:17)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:422:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
(node:87895) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:87895) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✔ Disable - find
✔ Disable - remove
```

**Comment by makinde** [comment]
Ah, it looks like [that error](https://stackoverflow.com/questions/37136204/mongoerror-ns-not-found-when-try-to-drop-collection) happens when the code drops a collection that's not there. I'm not sure why that's happening since the `await mongoose.connection.collections.newusers.drop();` line is within a `try/catch`. That said, I'm going to create an issue for this that should be resolved when I migrate `index.tests.js` to the new test structure.

**Comment by makinde** [comment]
#16

**Pull request merged**
